name: pyproximal
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.11.0
  - numpy>=1.21.0
  - scipy>=1.14.0
  - pylops>=2.0.0
  - scikit-image
  - matplotlib
  - typing_extensions
  - ipython
  - pytest
  - Sphinx
  - numpydoc
  - numba
  - icc_rt
  - pre-commit
  - autopep8
  - isort
  - black
  - pip:
    - bm4d
    - bm3d
    - pytest-runner
    - setuptools_scm
    - pooch
    - shibuya
    - sphinx-design
    - sphinx-gallery
    - sphinx-iconify
    - nbsphinx
    - sphinxemoji
    - image
    - flake8
    - mypy
