name: PyProx

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ] # temporarily removed macos-latest because of different behavior with numpy v2
        python-version: ["3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: Get history and tags for SCM versioning to work
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Install pyproximal
      run: |
        python -m setuptools_scm
        pip install .
    - name: Test with pytest
      run: |
        pytest