# This workflow uploads PyProx on PyPI using Twine when a release is created
# For more information see: https://github.com/python-attrs/attrs/blob/main/.github/workflows/pypi-package.yml
name: PyProximal-deploy

on:
  push:
    tags: ["*"]
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build and inspect package
        uses: hynek/build-and-inspect-python-package@v2

  release-test-pypi:
    name: Publish in-dev package to test.pypi.org
    if: github.repository_owner == 'PyLops' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: build-package
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download package
        uses: actions/download-artifact@v8
        with:
          name: Packages
          path: dist

      - name: Upload package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
          repository-url: https://test.pypi.org/legacy/

  release-pypi:
    name: Publish released package to pypi.org
    if: github.repository_owner == 'PyLops' && github.event.action == 'published'
    runs-on: ubuntu-latest
    needs: build-package
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download package
        uses: actions/download-artifact@v8
        with:
          name: Packages
          path: dist

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
