# This workflow runs Ruff on the PR
# For more information see: https://github.com/marketplace/actions/ruff-action
name: PyProximal-ruff

on: [push, pull_request]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: ruff Lint
        uses: astral-sh/ruff-action@v3
        with:
          args: >
            check pyproximal
            --line-length 88
            --ignore E203,E501,W503,E402
            --per-file-ignores "__init__.py:F401,F403,F405"
